### ISSUE TITLE
提个意见，能不能做一个地震速报的程序，不需要加地震预警这个功能

### ISSUE THREAD

**Issue by HLLF-FAN** [RainYangty/UDTW#2]
![image](https://github.com/RainYangty/UDTW/assets/107034178/f11c325f-773e-44ef-8933-7c6205486aa0)
![image](https://github.com/RainYangty/UDTW/assets/107034178/489f80f4-19e6-4503-b01e-07032a5e608c)
像这种

**Comment by RainYangty** [comment]
可修改config.json文件来达到此效果
