### ISSUE TITLE
钉钉webhook可以发送图片消息吗？我现在只能发image表情

### ISSUE THREAD

**Issue by HLLF-FAN** [RainYangty/UDTW#3]
![image](https://github.com/RainYangty/UDTW/assets/107034178/2c3976b1-2033-47fd-9393-ce7b41be8e09)
就像这样

**Comment by RainYangty** [comment]
目前我也是这样，可以向原作者提交问题

**Comment by HLLF-FAN** [comment]
![Screenshot_20240212_121404.jpg](https://github.com/RainYangty/UDTW/assets/107034178/87c33867-e811-4483-9893-8d65da7ea669)

OK了，我使用的md格式发送的就可以了
